# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f8147af5e75a0abdab282229592ee30ad87205a2f42753c31ec3c36f8e190b5516242d6f6ed27a32c305c7a270f895fad43ce56d0cb07d505e09f36c9b2ca66

test:
  secret_key_base: 9e78ac59964066594c83b91cea96cd95ee29674e768a2fd68f7b82c72325825198690382c1504deaabe6642410b575363c63ca5f391634ad20cbe3e347f59666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
